### ISSUE TITLE
Mulitple warnings - Update of alarm... taking over 10 seconds

### ISSUE THREAD

**Issue by tomoqv** [mgejke/hass-sectoralarm#1]
About every 15 minutes I get the following warning in the log. Not sure if it has any impact on the functionality, though.

```
Update of alarm_control_panel.sector_alarm_02602218 is taking over 10 seconds
14:54 core.py (WARNING)
Update of alarm_control_panel.sector_alarm_02602218 is taking over 10 seconds
14:38 core.py (WARNING)
Update of alarm_control_panel.sector_alarm_02602218 is taking over 10 seconds
13:52 core.py (WARNING)

```

**Comment by mgejke** [comment]
It takes quite a while to fetch the temperatures every now and then.

My guess is that the main unit fetches the temperatures from the senors every now and then and then caches it for a while, when the cache is too old it needs to fetch again. 

You can see the same behavior when using the app or logging in to the webpage, fetching temperatures is really slow.

**Comment by Vingen168** [comment]
Hi i have the same issue, are there any solution for this?
