### ISSUE TITLE
Error after upgrading to 0.98.x

### ISSUE THREAD

**Issue by phellarv** [mgejke/hass-sectoralarm#17]
Traceback (most recent call last):,
2019-08-30 12:34:59 ERROR (MainThread) [homeassistant.setup] Error during setup of component sector_alarm,
  File "/usr/src/homeassistant/homeassistant/setup.py", line 168, in _async_setup_component,
  File "/config/custom_components/sector_alarm/__init__.py", line 66, in async_setup,
    hass, processed_config,
    await sector_data.update(),
  File "/config/custom_components/sector_alarm/__init__.py", line 125, in update,
    *[task() for task in self._update_tasks]),
  File "/config/custom_components/sector_alarm/__init__.py", line 148, in _update_temperatures,
    temperatures = await self._async_sector.get_temperatures(),
  File "/usr/local/lib/python3.7/site-packages/asyncsector/asyncsector.py", line 76, in get_temperatures,
    return await get_json(request),
  File "/usr/local/lib/python3.7/site-packages/asyncsector/util.py", line 19, in get_json,
    raise Exception("Error from api: %s" % result),
Exception: Error from api: "INVALID_VERSION"

**Comment by toredash** [comment]
Most likely related to: https://github.com/mgejke/asyncsector/pull/11

**Comment by sebastian-steinmann** [comment]
Just add the parameter , "v1_1_70" to the constructor of the lib and your good to go. I'll see if I can make a PR tomorrow.

**Comment by phellarv** [comment]
> Just add the parameter , "v1_1_70" to the constructor of the lib and your good to go. I'll see if I can make a PR tomorrow.

Can you show an example on how to do this?

**Comment by phellarv** [comment]
No worries - Found it out.

**Comment by toredash** [comment]
@phellarv I think this is the point where people would be grateful if you shared your solution :)

**Comment by phellarv** [comment]
1) Open /config/custom_components/sector_alarm/__init__.py in an editor.
2) Change:
    async_sector = AsyncSector(session, config[DOMAIN].get(CONF_ALARM_ID),
                               config[DOMAIN].get(CONF_EMAIL),
                               config[DOMAIN].get(CONF_PASSWORD))
to:
    async_sector = AsyncSector(session, config[DOMAIN].get(CONF_ALARM_ID),
                               config[DOMAIN].get(CONF_EMAIL),
                               config[DOMAIN].get(CONF_PASSWORD),
                               version='v1_1_70')
3) Restart hassio

**Comment by mgejke** [comment]
I've fixed it so that you can set the version in the config file instead, that way you don't have to modify the code... 

But for some reason I'm not able to login and test it... Soon!

**Comment by mgejke** [comment]
Alright, there's a new config option now. The default is set to the current version, but hopefully it can be used in the future as long as the changes aren't breaking.

`version: 'v1_1_70'`
