### ISSUE TITLE
Configuration error when validating config

### ISSUE THREAD

**Issue by kristianwh** [mgejke/hass-sectoralarm#2]
Hi, thanks for a great component. I have a minor issue. When doing a configuration validation from the HA web-gui, I get this error:

Invalid config for [sector_alarm]: required key not provided @ data['platform']. Got None. (See ?, line ?). Please check the docs at https://home-assistant.io/components/sector_alarm/

No big deal, but this error results in that I can't restart home assistant from the webpage after making changes.

**Comment by mgejke** [comment]
I've seen other people with this problem, but I've not been able to reproduce it myself. I'll make some more effort to look for it when I get some time :)

**Comment by erikhakansson** [comment]
I have the same issue.

Worth noting is that the code set in configuration.yml does not work. I have to input the code manually each time.

**Comment by mgejke** [comment]
This should be fixed now!

@erikhakansson - The code thing is actually by design, it just verifies with the code you entered before trying to arm/disarm with Sector. If you really want to be able to arm/disarm without entering a code I could add an option for it.
