### ISSUE TITLE
Error from api: "INVALID_VERSION"

### ISSUE THREAD

**Issue by PalmMx** [mgejke/hass-sectoralarm#21]
My log is saying this:

2019-09-15 23:31:09 ERROR (MainThread) [homeassistant.setup] Error during setup of component sector_alarm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 168, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/sector_alarm/__init__.py", line 71, in async_setup
    await sector_data.update()
  File "/config/custom_components/sector_alarm/__init__.py", line 130, in update
    *[task() for task in self._update_tasks])
  File "/config/custom_components/sector_alarm/__init__.py", line 153, in _update_temperatures
    temperatures = await self._async_sector.get_temperatures()
  File "/usr/local/lib/python3.7/site-packages/asyncsector/asyncsector.py", line 76, in get_temperatures
    return await get_json(request)
  File "/usr/local/lib/python3.7/site-packages/asyncsector/util.py", line 19, in get_json
    raise Exception("Error from api: %s" % result)
Exception: Error from api: "INVALID_VERSION"

I guess this has something to do with the recently added version code..?
version: <version of the sector alarm api, default is 'v1_1_70'>

I also guess the default version 'v1_1_70' is not correct for my system?
How and where can I see what version I have?

Or, is this error due to a change made by Sector Alarm in their API which requires new/updated py-files?

I'm running 0.98.5 and have not been able to integrate this HASS-SectorAlarm component the last 1-2 week(s).

**Comment by mgejke** [comment]
It seems like the correct version is 'v1_1_71' at the moment.

**Comment by Lintan83** [comment]
> It seems like the correct version is 'v1_1_71' at the moment.

Where do i find what version is the correct when it change again?

**Comment by mgejke** [comment]
I think I remember someone posting a link somewhere here, but I can't find it now. 
What I did now was just to login using their web-interface and check the developer tools in chrome, the version string shows here and there.

**Comment by willeraab** [comment]
I have this in my config (hassio so should work in every similar installation I guess):

  - platform: command_line
    command: 'curl -ks https://minasidor.sectoralarm.se | grep "src=\"/Scripts/main\.js" | grep -o "v\d*_\d*_\d*"'
    name: 'Sector Alarm Version'
    scan_interval: 900
    value_template: '{{ value }}'

Then I have an automation to send me a notification when the value has changed. For a while I made auto updates of the config instead, but I reintroduced the manual config update step again since I am a bit of a control freak... :)

**Comment by PalmMx** [comment]
Thanks.
