### ISSUE TITLE
Invalid Config (!secret)

### ISSUE THREAD

**Issue by Thrimed** [mgejke/hass-sectoralarm#22]
"
The following components and platforms could not be set up:

    sector-alarm
"

When i try to save the login etc, in the secret.yml file.
Works fine if the details are in the configuration.yml...

**Comment by PalmMx** [comment]
> "
> The following components and platforms could not be set up:
> 
> ```
> sector-alarm
> ```
> 
> "
> 
> When i try to save the login etc, in the secret.yml file.
> Works fine if the details are in the configuration.yml...

Then you are not referring correct to the sectrets. This has never been an issue for me at least. Not with HASS-SectorAlarm and not with other components.

**Comment by Thrimed** [comment]
I will try again...
