### ISSUE TITLE
Install manual does not tell requirments

### ISSUE THREAD

**Issue by burner-** [mgejke/hass-sectoralarm#4]
It would save debugging if readme will tell also about requirments and howto install them

**Comment by burner-** [comment]
Without asyncsector  it fails to load module and to log it show that it does not find asyncsector. I try manually install it with pip and now it loads module but I did not manage get it work yet because finnish sector alarm use different domain for portal

**Comment by mgejke** [comment]
Are you trying to use this in home assistant or not? If you're not you should just use asyncsector instead.

**Comment by mgejke** [comment]
The asyncsector package should be downloaded by HA, if not, try a full restart of HA.
