### ISSUE TITLE
Looses state of alarm several times a day.

### ISSUE THREAD

**Issue by phellarv** [mgejke/hass-sectoralarm#5]
2018-10-25 23:21:00 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.sector_alarm_01108298 is taking over 10 seconds

And then the state of the alarm goes into unknown.

**Comment by mgejke** [comment]
It's the thermometers fault that it's slow, if you set them to false that won't happen. 
I also get those in my log, however, it doesn't get set to unknown... I'll see what I can find.

**Comment by phellarv** [comment]
Found the bug:
If you connect a lock to the alarm system you get the state of the lock as it is the latest entry in the history. If I try --history I get:

unlock                  2018-10-26T08:52:22
lock                    2018-10-26T07:41:41
unlock                  2018-10-26T07:41:36
disarmed    Familien    2018-10-26T06:30:33
partialarmedFamilien    2018-10-26T01:31:39

But without history it just return the latest state, which is lock, and that is translated to unknown.

**Comment by mgejke** [comment]
I've pushed a fix, please try it out and tell me if it works!

**Comment by phellarv** [comment]
It works perfectly. Very nice. Thanks for the fix.
